---
title: "Exploratory Data Analysis"
output: PDF_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("plotly")
```

## Suicide Rate By Mental Health in different countries

### Introduction

Every day there are many people commit suicide across the world and lots of the time people commit suicide due to there mental health and other personal issues too. I genuinely worry about people's mental health, particularly during and after COVID-19. Many people may have overlooked the seriousness of this problem despite the lock down's obvious negative effects on people's mental and psychological actions and perceptions. And maybe by employing code analysis, we can determine how strongly the epidemic and suicide rates are related.

### Table of Summary

-   The first table shows the suicide age rate per 100,000 population in different countries. The info was from the most recent dataset by WHO. From the dataset an pertinent observations that I found was how male suicide rate are higher then female by age.

| Location | Year | Gender | Avg_rate | Low_rate | High_rate |
|----------|------|--------|----------|----------|-----------|

|           |          |            |          |          |          |
|-----------|----------|------------|----------|----------|----------|
| **Japan** | **2019** | **Female** | **6.91** | **6.45** | **7.35** |

| Japan | 2019 | Male | 17.53 | 16.71 | 18.35 |
|-------|------|------|-------|-------|-------|

| Mexico | 2019 | Both sexes | 5.29 | 4.28 | 6.46 |
|--------|------|------------|------|------|------|

| Mexico | 2019 | Female | 2.18 | 1.73 | 2.70 |
|--------|------|--------|------|------|------|

| Mexico | 2019 | Male | 8.69 | 7.06 | 10.57 |
|--------|------|------|------|------|-------|

| Philippines | 2019 | Both sexes | 2.54 | 1.81 | 9.34 |
|-------------|------|------------|------|------|------|

| Philippines | 2019 | Female | 1.32 | 1.01 | 9.65 |
|-------------|------|--------|------|------|------|

| Philippines | 2019 | Male | 3.88 | 2.69 | 9.36 |
|-------------|------|------|------|------|------|

| Poland | 2019 | Both sexes | 9.30 | 7.34 | 11.75 |
|--------|------|------------|------|------|-------|

| Poland | 2019 | Female | 2.43 | 1.85 | 3.16 |
|--------|------|--------|------|------|------|

| Poland | 2019 | Male | 16.46 | 13.06 | 20.72 |
|--------|------|------|-------|-------|-------|

| Qatar | 2019 | Both sexes | 4.66 | 2.87 | 7.46 |
|-------|------|------------|------|------|------|

| Qatar | 2019 | Female | 1.69 | 1.01 | 2.63 |
|-------|------|--------|------|------|------|

| Qatar | 2019 | Male | 5.66 | 3.49 | 9.12 |
|-------|------|------|------|------|------|

| Singapore | 2019 | Both sexes | 9.65 | 7.77 | 11.77 |
|-----------|------|------------|------|------|-------|

| Singapore | 2019 | Female | 6.37 | 5.06 | 7.84 |
|-----------|------|--------|------|------|------|

| Singapore | 2019 | Male | 12.67 | 10.26 | 15.41 |
|-----------|------|------|-------|-------|-------|

| United States of America | 2019 | Both sexes | 14.51 | 13.56 | 19.35 |
|--------------------------|------|------------|-------|-------|-------|

| United States of America | 2019 | Female | 6.77 | 6.34 | 8.79 |
|--------------------------|------|--------|------|------|------|

| United States of America | 2019 | Male | 22.40 | 20.92 | 29.96 |
|--------------------------|------|------|-------|-------|-------|

-   The second table shows the different facilities that different countries has. Looking at the data I found that pertinent observations is how Japan has the most mental hospital compare to the other countries. Which I though United States should maybe would have more in comparison.

| Country | Year | residential_facilities | mental_facilities | daily_treatment |
|---------|------|------------------------|-------------------|-----------------|

| Cuba | 2016 | 1.213 | 0.166 | 0.445 |
|------|------|-------|-------|-------|

| Japan | 2016 | 0.366 | 8.314 | 3.759 |
|-------|------|-------|-------|-------|

| Mexico | 2016 | 0.012 | 0.029 | 0.079 |
|--------|------|-------|-------|-------|

| Morocco | 2016 | 0.069 | 0.032 | 0.101 |
|---------|------|-------|-------|-------|

| Poland | 2016 | NA  | 0.125 | 0.716 |
|--------|------|-----|-------|-------|

| Qatar | 2016 | 0.076 | 0.038 | 0.115 |
|-------|------|-------|-------|-------|

| Singapore | 2016 | 0.054 | 0.018 | 0.163 |
|-----------|------|-------|-------|-------|

| United States of America | 2016 | NA  | 0.189 | NA  |
|--------------------------|------|-----|-------|-----|
